quarkus:
  s3:
    endpoint-override: http://localhost:4566
    path-style-access: true
    aws:
      credentials:
        type: static
        static-provider:
          access-key-id: ${AWS_KEY}
          secret-access-key: ${AWS_SECRET}
opensearch:
  aws:
    region: "us-east-1"
    service: "es"
  max-concurrency: 300
  connection-acquisition-timeout: 60s
  hosts: "localhost"
  port: 9200
aws:
  enabled: false
