quarkus:
  fault-tolerance:
    com.seregamazur.pulse.controller.DashboardController:
      rate-limit:
        enabled: true
        value: 50
        window: 60
        time-unit: SECONDS
      circuitbreaker:
        request-volume: 10
        failure-ratio: 0.5
        delay: 5
        delay-unit: SECONDS
  http:
    record-request-start-time: true
    access-log:
      pattern: "%h %r %s %t %Dms"
      enabled: true
    host: 0.0.0.0
    route-display: true
  native:
    container-build: true
    builder-image: quay.io/quarkus/ubi-quarkus-graalvmce-builder-image:jdk-21
  console:
    color: false
  log:
    console:
      enable: true
      format: "%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n"
    level: INFO
    category:
      "io.quarkus":
        level: WARN
      "org.opensearch":
        level: DEBUG
      "io.quarkus.http.access-log":
        level: INFO

firebase:
  project:
    number: 522383639167
  web:
    appId: 1:522383639167:web:168e0cdc9b4f12206bb54a
  appcheck:
    jwks: https://firebaseappcheck.googleapis.com/v1/jwks
